neighbor:
  eps: [0.0001, 0.001, 0.01, 0]
  min_cluster_size: [3, 4, 5, 6, 7, 8, 9, 10]
  min_sample_size: [1, 2, 3, 4, 5,]
  cluster_selection_method: 'leaf' # leaf or eom
  used_cols: ['rel_sasa', 'depth', 'hse_up', 'hse_down', 'dssp_phi_sin', 'dssp_phi_cos', 'dssp_psi_sin', 'dssp_psi_cos', 'dssp_alpha_sin', 'dssp_alpha_cos', 'aa1_PCA0', 'aa1_PCA1' ]

residue:
  eps: [0.0001, 0.001, 0.01, 0]
  min_cluster_size: [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
  min_sample_size: [1, 2, 3, 4, 5,]
  cluster_selection_method: 'leaf' # leaf or eom
  used_cols: ['rel_sasa', 'depth', 'hse_up', 'hse_down', 'dssp_phi_sin', 'dssp_phi_cos', 'dssp_alpha_sin', 'dssp_alpha_cos', 'aa1_PCA0', 'aa1_PCA1' ]
