
# ====================
# Augmentation Setting
# ====================
graph_augmentation:
  aug_anchor_ratio: 0.10
  hop_ratios: [0.9, 0.8, 0.5, 0.5, 0.5]
  aug_min_node: 30

# ====================
# Model Setting
# ====================
model_param:
  hidden_dims: [64, 128, 256]
  drop_prob: 0.5
  activation: prelu # not implement yet
  edge_att: null # weight name (null or cleaned_total_energy)
  emb_dim:
    dssp_sec_struct: 16
    dssp_helix_3_10: 4
    dssp_helix_alpha: 4
    dssp_helix_pi: 4
    dssp_helix_pp: 8
    dssp_bend: 4
    dssp_chirality: 4
    dssp_sheet: 32
    dssp_strand: 32
    # dssp_ladder_1: 128
    # dssp_ladder_2: 128